# Generated by Django 5.2.7 on 2025-11-17 12:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilisateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePropose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_module', models.CharField(max_length=20, verbose_name='Code du module')),
                ('nom_module', models.CharField(max_length=200, verbose_name='Nom du module')),
                ('ue_nom', models.CharField(blank=True, help_text="Nom de l'UE à laquelle appartient ce module", max_length=200, verbose_name="Unité d'Enseignement")),
                ('volume_heure_cours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Volume Heures CM')),
                ('volume_heure_td', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Volume Heures TD')),
                ('taux_horaire_cours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Taux Horaire CM (FCFA)')),
                ('taux_horaire_td', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Taux Horaire TD (FCFA)')),
                ('est_valide', models.BooleanField(default=False, help_text='Indique si le module a été validé par le responsable RH', verbose_name='Validé par RH')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
            ],
            options={
                'verbose_name': 'Module Proposé',
                'verbose_name_plural': 'Modules Proposés',
                'ordering': ['code_module'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID API')),
                ('nom', models.CharField(max_length=300, verbose_name='Nom de la classe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('annee_academique', models.CharField(max_length=50, verbose_name='Année académique')),
                ('annee_etat', models.CharField(blank=True, max_length=50, verbose_name="État de l'année")),
                ('filiere', models.CharField(max_length=200, verbose_name='Filière')),
                ('niveau', models.CharField(max_length=100, verbose_name='Niveau')),
                ('departement', models.CharField(max_length=100, verbose_name='Département')),
                ('nombre_groupes', models.IntegerField(default=0, verbose_name='Nombre de groupes')),
                ('effectif_total', models.IntegerField(default=0, verbose_name='Effectif total')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Données brutes API')),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière synchronisation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Classe active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='Utilisateur.section', verbose_name='Section IIPEA')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['filiere', 'niveau'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_heure_cours', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Volume heures cours contractuel')),
                ('volume_heure_td', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Volume heures TD contractuel')),
                ('taux_horaire_cours', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taux horaire cours (FCFA)')),
                ('taux_horaire_td', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taux horaire TD (FCFA)')),
                ('type_enseignement', models.CharField(choices=[('NORMAL', 'Cours normal'), ('TRONC_COMMUN', 'Tronc commun')], default='NORMAL', max_length=20, verbose_name="Type d'enseignement")),
                ('date_debut_prevue', models.DateField(blank=True, null=True, verbose_name='Date de début prévue')),
                ('date_debut_reelle', models.DateField(blank=True, null=True, verbose_name='Date de début réelle')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('status', models.CharField(choices=[('VALIDATED', 'Validé'), ('READY_TO_START', 'Prêt à démarrer'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('PENDING_DOCUMENTS', 'En attente documents'), ('READY_FOR_PAYMENT', 'Prêt pour paiement'), ('PAID', 'Payé'), ('CANCELLED', 'Annulé')], default='VALIDATED', max_length=30, verbose_name='Statut')),
                ('date_validation', models.DateTimeField(verbose_name='Date de validation')),
                ('date_demarrage', models.DateTimeField(blank=True, null=True, verbose_name='Date de démarrage')),
                ('support_cours_uploaded', models.BooleanField(default=False, verbose_name='Support de cours chargé')),
                ('syllabus_uploaded', models.BooleanField(default=False, verbose_name='Syllabus chargé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='Gestion.classe', verbose_name='Classe principale')),
                ('classes_tronc_commun', models.ManyToManyField(blank=True, related_name='contrats_tronc_commun', to='Gestion.classe', verbose_name='Classes en tronc commun')),
                ('demarre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_demarres', to=settings.AUTH_USER_MODEL, verbose_name='Démarré par')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='Utilisateur.professeur', verbose_name='Professeur')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_validation'],
            },
        ),
        migrations.CreateModel(
            name='DocumentContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('SUPPORT_COURS', 'Support de cours'), ('SYLLABUS', 'Syllabus'), ('FICHE_CONTRAT', 'Fiche de contrat'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('fichier', models.FileField(upload_to='contrats/documents/%Y/%m/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('est_valide', models.BooleanField(default=False, verbose_name='Est validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_charges', to=settings.AUTH_USER_MODEL, verbose_name='Chargé par')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Gestion.contrat', verbose_name='Contrat')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Document de contrat',
                'verbose_name_plural': 'Documents de contrat',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID API')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du groupe')),
                ('code', models.CharField(max_length=50, verbose_name='Code du groupe')),
                ('effectif', models.IntegerField(default=0, verbose_name='Effectif')),
                ('capacite_max', models.IntegerField(default=0, verbose_name='Capacité maximale')),
                ('taux_remplissage', models.FloatField(default=0.0, verbose_name='Taux de remplissage (%)')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Données brutes API')),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière synchronisation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Groupe actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='Gestion.classe', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['classe', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='contrat',
            name='groupes_selectionnes',
            field=models.ManyToManyField(blank=True, related_name='contrats', to='Gestion.groupe', verbose_name='Groupes sélectionnés'),
        ),
        migrations.CreateModel(
            name='Maquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID API')),
                ('filiere_id', models.IntegerField(verbose_name='ID Filière')),
                ('niveau_id', models.IntegerField(verbose_name='ID Niveau')),
                ('anneeacademique_id', models.IntegerField(verbose_name='ID Année académique')),
                ('filiere_nom', models.CharField(max_length=200, verbose_name='Nom de la filière')),
                ('filiere_sigle', models.CharField(max_length=20, verbose_name='Sigle de la filière')),
                ('niveau_libelle', models.CharField(max_length=100, verbose_name='Libellé du niveau')),
                ('annee_academique', models.CharField(max_length=50, verbose_name='Année académique')),
                ('parcour', models.CharField(blank=True, max_length=100, verbose_name='Parcours')),
                ('date_creation_api', models.DateTimeField(blank=True, null=True, verbose_name='Date création (API)')),
                ('unites_enseignement', models.JSONField(blank=True, default=list, verbose_name="Unités d'enseignement")),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Données brutes API')),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière synchronisation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Maquette active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquettes', to='Gestion.classe', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Maquette',
                'verbose_name_plural': 'Maquettes',
                'ordering': ['filiere_nom', 'niveau_libelle'],
            },
        ),
        migrations.AddField(
            model_name='contrat',
            name='maquette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='Gestion.maquette', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='module_propose',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='Gestion.modulepropose', verbose_name='Module proposé'),
        ),
        migrations.CreateModel(
            name='PaiementContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_brut', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant brut (FCFA)')),
                ('montant_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Impôts, cotisations, etc.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Déductions (FCFA)')),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant net (FCFA)')),
                ('mode_paiement', models.CharField(blank=True, choices=[('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20, null=True, verbose_name='Mode de paiement')),
                ('reference_paiement', models.CharField(blank=True, help_text='Numéro de chèque, référence virement, etc.', max_length=100, verbose_name='Référence de paiement')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('PROCESSING', 'En cours de traitement'), ('PAID', 'Payé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('raison_rejet', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_approuves', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Gestion.contrat', verbose_name='Contrat')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('paye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Payé par')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Utilisateur.professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Paiement de contrat',
                'verbose_name_plural': 'Paiements de contrats',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField(verbose_name='Date de la séance')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('heures_cours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Heures de cours')),
                ('heures_td', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Heures de TD')),
                ('est_valide', models.BooleanField(default=True, verbose_name='Est validé')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='Gestion.contrat', verbose_name='Contrat')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-date_seance'],
            },
        ),
        migrations.CreateModel(
            name='PreContrat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Unique')),
                ('reference', models.CharField(blank=True, help_text='Référence unique du précontrat (ex: PC-2024-001)', max_length=20, unique=True, verbose_name='Référence')),
                ('classe_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom de la classe')),
                ('classe_niveau', models.CharField(blank=True, max_length=50, verbose_name='Niveau de la classe')),
                ('classe_filiere', models.CharField(blank=True, max_length=100, verbose_name='Filière de la classe')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis pour validation'), ('UNDER_REVIEW', 'En cours de révision'), ('VALIDATED', 'Validé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('raison_rejet', models.TextField(blank=True, help_text='Raison du rejet si le précontrat est rejeté', verbose_name='Raison du rejet')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('annee_academique', models.CharField(blank=True, help_text='Ex: 2024-2025', max_length=9, verbose_name='Année académique')),
                ('classe', models.ForeignKey(help_text='Classe pour laquelle le précontrat est créé', on_delete=django.db.models.deletion.PROTECT, related_name='precontrats', to='Gestion.classe', verbose_name='Classe')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precontrats_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('professeur', models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'PROFESSEUR'}, on_delete=django.db.models.deletion.PROTECT, related_name='precontrats', to=settings.AUTH_USER_MODEL, verbose_name='Professeur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precontrats_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Précontrat',
                'verbose_name_plural': 'Précontrats',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='modulepropose',
            name='pre_contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_proposes', to='Gestion.precontrat', verbose_name='Précontrat'),
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Créé'), ('SUBMITTED', 'Soumis'), ('VALIDATED', 'Validé'), ('STARTED', 'Démarré'), ('COMPLETED', 'Terminé'), ('READY_FOR_PAYMENT', 'Prêt pour paiement'), ('PAYMENT_CREATED', 'Paiement créé'), ('PAYMENT_APPROVED', 'Paiement approuvé'), ('PAID', 'Payé'), ('PAYMENT_REJECTED', 'Paiement rejeté'), ('CANCELLED', 'Annulé'), ('DOCUMENT_UPLOADED', 'Document chargé'), ('OTHER', 'Autre')], max_length=30, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Gestion.contrat', verbose_name='Contrat')),
                ('module_propose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Gestion.modulepropose', verbose_name='Module proposé')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Gestion.paiementcontrat', verbose_name='Paiement')),
                ('pre_contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Gestion.precontrat', verbose_name='Pré-contrat')),
            ],
            options={
                'verbose_name': "Journal d'action",
                'verbose_name_plural': 'Journal des actions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['external_id'], name='Gestion_cla_externa_6df3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['filiere'], name='Gestion_cla_filiere_b55bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['niveau'], name='Gestion_cla_niveau_413471_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['departement'], name='Gestion_cla_departe_c1ff33_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['last_synced'], name='Gestion_cla_last_sy_753408_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcontrat',
            index=models.Index(fields=['contrat', 'type_document'], name='Gestion_doc_contrat_24cd48_idx'),
        ),
        migrations.AddIndex(
            model_name='groupe',
            index=models.Index(fields=['external_id'], name='Gestion_gro_externa_753eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='groupe',
            index=models.Index(fields=['classe', 'is_active'], name='Gestion_gro_classe__10ae99_idx'),
        ),
        migrations.AddIndex(
            model_name='groupe',
            index=models.Index(fields=['-last_synced'], name='Gestion_gro_last_sy_239082_idx'),
        ),
        migrations.AddIndex(
            model_name='maquette',
            index=models.Index(fields=['external_id'], name='Gestion_maq_externa_456fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='maquette',
            index=models.Index(fields=['filiere_id'], name='Gestion_maq_filiere_cef3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='maquette',
            index=models.Index(fields=['niveau_id'], name='Gestion_maq_niveau__b1caf3_idx'),
        ),
        migrations.AddIndex(
            model_name='maquette',
            index=models.Index(fields=['anneeacademique_id'], name='Gestion_maq_anneeac_793de0_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['professeur', 'status'], name='Gestion_con_profess_b8f5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['classe', 'status'], name='Gestion_con_classe__09108a_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['status'], name='Gestion_con_status_8bffd7_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['-date_validation'], name='Gestion_con_date_va_918205_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementcontrat',
            index=models.Index(fields=['professeur', 'status'], name='Gestion_pai_profess_3cf34c_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementcontrat',
            index=models.Index(fields=['status'], name='Gestion_pai_status_877d39_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementcontrat',
            index=models.Index(fields=['-date_creation'], name='Gestion_pai_date_cr_a41ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['contrat', '-date_seance'], name='Gestion_poi_contrat_2c41eb_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['-date_seance'], name='Gestion_poi_date_se_98e7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='precontrat',
            index=models.Index(fields=['status', 'date_creation'], name='Gestion_pre_status_599098_idx'),
        ),
        migrations.AddIndex(
            model_name='precontrat',
            index=models.Index(fields=['professeur', 'classe'], name='Gestion_pre_profess_51ec9d_idx'),
        ),
        migrations.AddIndex(
            model_name='precontrat',
            index=models.Index(fields=['reference'], name='Gestion_pre_referen_0b5ced_idx'),
        ),
        migrations.AddIndex(
            model_name='modulepropose',
            index=models.Index(fields=['pre_contrat', 'est_valide'], name='Gestion_mod_pre_con_4355d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modulepropose',
            unique_together={('pre_contrat', 'code_module')},
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['contrat', '-timestamp'], name='Gestion_act_contrat_ee72ea_idx'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['-timestamp'], name='Gestion_act_timesta_dfc479_idx'),
        ),
    ]
