# Generated by Django 5.2.7 on 2025-11-24 19:28

import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Créé'), ('SUBMITTED', 'Soumis'), ('VALIDATED', 'Validé'), ('STARTED', 'Démarré'), ('COMPLETED', 'Terminé'), ('READY_FOR_PAYMENT', 'Prêt pour paiement'), ('PAYMENT_CREATED', 'Paiement créé'), ('PAYMENT_APPROVED', 'Paiement approuvé'), ('PAID', 'Payé'), ('PAYMENT_REJECTED', 'Paiement rejeté'), ('CANCELLED', 'Annulé'), ('DOCUMENT_UPLOADED', 'Document chargé'), ('OTHER', 'Autre')], max_length=30, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
            ],
            options={
                'verbose_name': "Journal d'action",
                'verbose_name_plural': 'Journal des actions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID API')),
                ('nom', models.CharField(max_length=300, verbose_name='Nom de la classe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('annee_academique', models.CharField(max_length=50, verbose_name='Année académique')),
                ('annee_etat', models.CharField(blank=True, max_length=50, verbose_name="État de l'année")),
                ('filiere', models.CharField(max_length=200, verbose_name='Filière')),
                ('niveau', models.CharField(max_length=100, verbose_name='Niveau')),
                ('departement', models.CharField(max_length=100, verbose_name='Département')),
                ('nombre_groupes', models.IntegerField(default=0, verbose_name='Nombre de groupes')),
                ('effectif_total', models.IntegerField(default=0, verbose_name='Effectif total')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Données brutes API')),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière synchronisation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Classe active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['filiere', 'niveau'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Référence unique générée automatiquement', max_length=20, unique=True, verbose_name='Référence du contrat')),
                ('volume_heure_cours', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Volume heures cours contractuel')),
                ('volume_heure_td', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Volume heures TD contractuel')),
                ('taux_horaire_cours', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taux horaire cours (FCFA)')),
                ('taux_horaire_td', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taux horaire TD (FCFA)')),
                ('type_enseignement', models.CharField(choices=[('NORMAL', 'Cours normal'), ('TRONC_COMMUN', 'Tronc commun')], default='NORMAL', max_length=20, verbose_name="Type d'enseignement")),
                ('date_debut_prevue', models.DateField(blank=True, null=True, verbose_name='Date de début prévue')),
                ('date_debut_reelle', models.DateField(blank=True, null=True, verbose_name='Date de début réelle')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('status', models.CharField(choices=[('VALIDATED', 'Validé'), ('READY_TO_START', 'Prêt à démarrer'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('PENDING_DOCUMENTS', 'En attente documents'), ('READY_FOR_PAYMENT', 'Prêt pour paiement'), ('PAID', 'Payé'), ('CANCELLED', 'Annulé')], default='VALIDATED', max_length=30, verbose_name='Statut')),
                ('date_validation', models.DateTimeField(verbose_name='Date de validation')),
                ('date_demarrage', models.DateTimeField(blank=True, null=True, verbose_name='Date de démarrage')),
                ('support_cours_uploaded', models.BooleanField(default=False, verbose_name='Support de cours chargé')),
                ('syllabus_uploaded', models.BooleanField(default=False, verbose_name='Syllabus chargé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_validation'],
            },
        ),
        migrations.CreateModel(
            name='DocumentContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('SUPPORT_COURS', 'Support de cours'), ('SYLLABUS', 'Syllabus'), ('FICHE_CONTRAT', 'Fiche de contrat'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('fichier', models.FileField(upload_to='contrats/documents/%Y/%m/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('est_valide', models.BooleanField(default=False, verbose_name='Est validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document de contrat',
                'verbose_name_plural': 'Documents de contrat',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID API')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du groupe')),
                ('code', models.CharField(max_length=50, verbose_name='Code du groupe')),
                ('effectif', models.IntegerField(default=0, verbose_name='Effectif')),
                ('capacite_max', models.IntegerField(default=0, verbose_name='Capacité maximale')),
                ('taux_remplissage', models.FloatField(default=0.0, verbose_name='Taux de remplissage (%)')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Données brutes API')),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière synchronisation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Groupe actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['classe', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Maquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID API')),
                ('filiere_id', models.IntegerField(verbose_name='ID Filière')),
                ('niveau_id', models.IntegerField(verbose_name='ID Niveau')),
                ('anneeacademique_id', models.IntegerField(verbose_name='ID Année académique')),
                ('filiere_nom', models.CharField(max_length=200, verbose_name='Nom de la filière')),
                ('filiere_sigle', models.CharField(max_length=20, verbose_name='Sigle de la filière')),
                ('niveau_libelle', models.CharField(max_length=100, verbose_name='Libellé du niveau')),
                ('annee_academique', models.CharField(max_length=50, verbose_name='Année académique')),
                ('parcour', models.CharField(blank=True, max_length=100, verbose_name='Parcours')),
                ('date_creation_api', models.DateTimeField(blank=True, null=True, verbose_name='Date création (API)')),
                ('unites_enseignement', models.JSONField(blank=True, default=list, verbose_name="Unités d'enseignement")),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Données brutes API')),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière synchronisation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Maquette active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Maquette',
                'verbose_name_plural': 'Maquettes',
                'ordering': ['filiere_nom', 'niveau_libelle'],
            },
        ),
        migrations.CreateModel(
            name='ModulePropose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_module', models.CharField(max_length=20, verbose_name='Code du module')),
                ('nom_module', models.CharField(max_length=200, verbose_name='Nom du module')),
                ('ue_nom', models.CharField(blank=True, help_text="Nom de l'UE à laquelle appartient ce module", max_length=200, verbose_name="Unité d'Enseignement")),
                ('volume_heure_cours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Volume Heures CM')),
                ('volume_heure_td', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Volume Heures TD')),
                ('taux_horaire_cours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Taux Horaire CM (FCFA)')),
                ('taux_horaire_td', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Taux Horaire TD (FCFA)')),
                ('est_valide', models.BooleanField(default=False, help_text='Indique si le module a été validé par le responsable RH', verbose_name='Validé par RH')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
            ],
            options={
                'verbose_name': 'Module Proposé',
                'verbose_name_plural': 'Modules Proposés',
                'ordering': ['code_module'],
            },
        ),
        migrations.CreateModel(
            name='PaiementContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_brut', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant brut (FCFA)')),
                ('montant_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Impôts, cotisations, etc.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Déductions (FCFA)')),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant net (FCFA)')),
                ('mode_paiement', models.CharField(blank=True, choices=[('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20, null=True, verbose_name='Mode de paiement')),
                ('reference_paiement', models.CharField(blank=True, help_text='Numéro de chèque, référence virement, etc.', max_length=100, verbose_name='Référence de paiement')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('PROCESSING', 'En cours de traitement'), ('PAID', 'Payé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('raison_rejet', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paiement de contrat',
                'verbose_name_plural': 'Paiements de contrats',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField(verbose_name='Date de la séance')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('heures_cours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Heures de cours')),
                ('heures_td', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Heures de TD')),
                ('est_valide', models.BooleanField(default=True, verbose_name='Est validé')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-date_seance'],
            },
        ),
        migrations.CreateModel(
            name='PreContrat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Unique')),
                ('reference', models.CharField(blank=True, help_text='Référence unique du précontrat (ex: PC-2024-001)', max_length=20, unique=True, verbose_name='Référence')),
                ('classe_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom de la classe')),
                ('classe_niveau', models.CharField(blank=True, max_length=50, verbose_name='Niveau de la classe')),
                ('classe_filiere', models.CharField(blank=True, max_length=100, verbose_name='Filière de la classe')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis pour validation'), ('UNDER_REVIEW', 'En cours de révision'), ('VALIDATED', 'Validé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('notes_validation', models.TextField(blank=True, help_text='Notes laissées par le validateur RH', verbose_name='Notes de validation')),
                ('raison_rejet', models.TextField(blank=True, help_text='Raison du rejet si le précontrat est rejeté', verbose_name='Raison du rejet')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('annee_academique', models.CharField(blank=True, help_text='Ex: 2024-2025', max_length=9, verbose_name='Année académique')),
            ],
            options={
                'verbose_name': 'Précontrat',
                'verbose_name_plural': 'Précontrats',
                'ordering': ['-date_creation'],
            },
        ),
    ]
