# Generated by Django 5.2.7 on 2025-11-16 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion', '0001_initial'),
        ('Utilisateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='classe',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='Utilisateur.section', verbose_name='Section IIPEA'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='Gestion.classe', verbose_name='Classe principale'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='classes_tronc_commun',
            field=models.ManyToManyField(blank=True, related_name='contrats_tronc_commun', to='Gestion.classe', verbose_name='Classes en tronc commun'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='demarre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_demarres', to=settings.AUTH_USER_MODEL, verbose_name='Démarré par'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='Utilisateur.professeur', verbose_name='Professeur'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='valide_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Gestion.contrat', verbose_name='Contrat'),
        ),
        migrations.AddField(
            model_name='documentcontrat',
            name='charge_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_charges', to=settings.AUTH_USER_MODEL, verbose_name='Chargé par'),
        ),
        migrations.AddField(
            model_name='documentcontrat',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Gestion.contrat', verbose_name='Contrat'),
        ),
        migrations.AddField(
            model_name='documentcontrat',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='maquette',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquettes', to='Gestion.classe', verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='maquette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='Gestion.maquette', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='module_propose',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='Gestion.modulepropose', verbose_name='Module proposé'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='module_propose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Gestion.modulepropose', verbose_name='Module proposé'),
        ),
        migrations.AddField(
            model_name='paiementcontrat',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_approuves', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='paiementcontrat',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Gestion.contrat', verbose_name='Contrat'),
        ),
        migrations.AddField(
            model_name='paiementcontrat',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='paiementcontrat',
            name='paye_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Payé par'),
        ),
        migrations.AddField(
            model_name='paiementcontrat',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Utilisateur.professeur', verbose_name='Professeur'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Gestion.paiementcontrat', verbose_name='Paiement'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='Gestion.contrat', verbose_name='Contrat'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='enregistre_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
        migrations.AddField(
            model_name='precontrat',
            name='classe',
            field=models.ForeignKey(help_text='Classe pour laquelle le précontrat est créé', on_delete=django.db.models.deletion.PROTECT, related_name='precontrats', to='Gestion.classe', verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='precontrat',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precontrats_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='precontrat',
            name='professeur',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'PROFESSEUR'}, on_delete=django.db.models.deletion.PROTECT, related_name='precontrats', to=settings.AUTH_USER_MODEL, verbose_name='Professeur'),
        ),
        migrations.AddField(
            model_name='precontrat',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precontrats_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='modulepropose',
            name='pre_contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_proposes', to='Gestion.precontrat', verbose_name='Précontrat'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='pre_contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Gestion.precontrat', verbose_name='Pré-contrat'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['external_id'], name='Gestion_cla_externa_6df3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['filiere'], name='Gestion_cla_filiere_b55bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['niveau'], name='Gestion_cla_niveau_413471_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['departement'], name='Gestion_cla_departe_c1ff33_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['last_synced'], name='Gestion_cla_last_sy_753408_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcontrat',
            index=models.Index(fields=['contrat', 'type_document'], name='Gestion_doc_contrat_24cd48_idx'),
        ),
        migrations.AddIndex(
            model_name='maquette',
            index=models.Index(fields=['external_id'], name='Gestion_maq_externa_456fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='maquette',
            index=models.Index(fields=['filiere_id'], name='Gestion_maq_filiere_cef3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='maquette',
            index=models.Index(fields=['niveau_id'], name='Gestion_maq_niveau__b1caf3_idx'),
        ),
        migrations.AddIndex(
            model_name='maquette',
            index=models.Index(fields=['anneeacademique_id'], name='Gestion_maq_anneeac_793de0_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['professeur', 'status'], name='Gestion_con_profess_b8f5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['classe', 'status'], name='Gestion_con_classe__09108a_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['status'], name='Gestion_con_status_8bffd7_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['-date_validation'], name='Gestion_con_date_va_918205_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementcontrat',
            index=models.Index(fields=['professeur', 'status'], name='Gestion_pai_profess_3cf34c_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementcontrat',
            index=models.Index(fields=['status'], name='Gestion_pai_status_877d39_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementcontrat',
            index=models.Index(fields=['-date_creation'], name='Gestion_pai_date_cr_a41ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['contrat', '-date_seance'], name='Gestion_poi_contrat_2c41eb_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['-date_seance'], name='Gestion_poi_date_se_98e7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='precontrat',
            index=models.Index(fields=['status', 'date_creation'], name='Gestion_pre_status_599098_idx'),
        ),
        migrations.AddIndex(
            model_name='precontrat',
            index=models.Index(fields=['professeur', 'classe'], name='Gestion_pre_profess_51ec9d_idx'),
        ),
        migrations.AddIndex(
            model_name='precontrat',
            index=models.Index(fields=['reference'], name='Gestion_pre_referen_0b5ced_idx'),
        ),
        migrations.AddIndex(
            model_name='modulepropose',
            index=models.Index(fields=['pre_contrat', 'est_valide'], name='Gestion_mod_pre_con_4355d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modulepropose',
            unique_together={('pre_contrat', 'code_module')},
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['contrat', '-timestamp'], name='Gestion_act_contrat_ee72ea_idx'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['-timestamp'], name='Gestion_act_timesta_dfc479_idx'),
        ),
    ]
