# Generated by Django 5.2.7 on 2025-11-24 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='pre_contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='Gestion.precontrat', verbose_name='Pré-contrat'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence unique générée automatiquement', max_length=30, unique=True, verbose_name='Référence du contrat'),
        ),
    ]
