# Generated by Django 5.2.7 on 2025-11-17 01:11

import Utilisateur.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('IIPEA YAKRO', 'IIPEA YAKRO'), ('IIPEA ABOBO', 'IIPEA ABOBO'), ('IIPEA RIVIERA 2', 'IIPEA RIVIERA 2')], max_length=20, unique=True, verbose_name='Nom de la section')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[Utilisateur.models.validate_phone_number], verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('responsable_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom du responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Section active')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Adresse email utilisée pour la connexion', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Adresse email')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('RESP_PEDA', 'Responsable Pédagogique'), ('RESP_RH', 'Responsable Ressources Humaines'), ('PROFESSEUR', 'Professeur'), ('INFORMATICIEN', 'Service Informatique'), ('COMPTABLE', 'Comptable'), ('SERVICE_DATA', 'Service Data')], max_length=15, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[Utilisateur.models.validate_phone_number], verbose_name='Téléphone')),
                ('is_active_user', models.BooleanField(default=True, help_text="Décochez pour suspendre temporairement l'accès de l'utilisateur", verbose_name='Utilisateur actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('last_section_access', models.DateTimeField(blank=True, null=True, verbose_name='Dernier accès section')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('section_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_principaux', to='Utilisateur.section', verbose_name='Section principale')),
                ('sections', models.ManyToManyField(blank=True, related_name='utilisateurs_sections', to='Utilisateur.section', verbose_name='Sections associées')),
                ('sections_autorisees', models.ManyToManyField(blank=True, related_name='utilisateurs_autorises', to='Utilisateur.section', verbose_name='Sections autorisées')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Professeur', 'Professeur'), ('Doctorant', 'Doctorant'), ('Docteur', 'Docteur')], default='Professeur', max_length=50, verbose_name='Grade')),
                ('statut', models.CharField(choices=[('Vacataire', 'Vacataire'), ('Titulaire', 'Titulaire')], default='Vacataire', max_length=50, verbose_name='Statut')),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='Masculin', max_length=50, verbose_name='Genre')),
                ('nationalite', models.CharField(blank=True, max_length=100, verbose_name='Nationalité')),
                ('numero_cni', models.CharField(blank=True, max_length=20, verbose_name='Numéro CNI')),
                ('situation_matrimoniale', models.CharField(choices=[('Marié', 'Marié'), ('Célibataire', 'Célibataire'), ('Divorcé', 'Divorcé'), ('Veuf', 'Veuf')], default='Célibataire', max_length=100, verbose_name='Situation matrimoniale')),
                ('domicile', models.CharField(blank=True, max_length=200, verbose_name='Adresse de domicile')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('matricule', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Matricule')),
                ('specialite', models.CharField(blank=True, max_length=100, verbose_name='Spécialité')),
                ('diplome', models.CharField(blank=True, max_length=100, verbose_name='Diplôme')),
                ('annee_experience', models.IntegerField(default=0, verbose_name="Année d'expérience")),
                ('photo', models.ImageField(blank=True, help_text='Format accepté: JPG, PNG (max 10MB)', null=True, upload_to=Utilisateur.models.professeur_photo_path, validators=[Utilisateur.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Photo de profil')),
                ('cni_document', models.FileField(blank=True, help_text='Format accepté: PDF, DOC, DOCX, JPG, PNG (max 10MB)', null=True, upload_to=Utilisateur.models.professeur_document_path, validators=[Utilisateur.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='CNI')),
                ('rib_document', models.FileField(blank=True, help_text='Format accepté: PDF, DOC, DOCX, JPG, PNG (max 10MB)', null=True, upload_to=Utilisateur.models.professeur_document_path, validators=[Utilisateur.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='RIB')),
                ('cv_document', models.FileField(blank=True, help_text='Format accepté: PDF, DOC, DOCX (max 10MB)', null=True, upload_to=Utilisateur.models.professeur_document_path, validators=[Utilisateur.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='CV')),
                ('diplome_document', models.FileField(blank=True, help_text='Format accepté: PDF, DOC, DOCX, JPG, PNG (max 10MB)', null=True, upload_to=Utilisateur.models.professeur_document_path, validators=[Utilisateur.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Diplôme')),
                ('photo_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('cni_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('rib_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('cv_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('diplome_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('date_embauche', models.DateField(auto_now_add=True, null=True, verbose_name="Date d'embauche")),
                ('is_active', models.BooleanField(default=True, verbose_name='Professeur actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('section_active', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professeurs_actifs', to='Utilisateur.section', verbose_name='Section active')),
                ('sections', models.ManyToManyField(related_name='professeurs', to='Utilisateur.section', verbose_name="Sections d'enseignement")),
                ('user', models.OneToOneField(limit_choices_to={'role': 'PROFESSEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='professeur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Comptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, help_text='Date de naissance du comptable', null=True, verbose_name='Date de naissance')),
                ('matricule', models.CharField(blank=True, help_text='Matricule unique du comptable (généré automatiquement si vide)', max_length=50, unique=True, verbose_name='Matricule')),
                ('code_unique', models.CharField(default=Utilisateur.models.generate_unique_code, help_text="Code d'identification unique généré automatiquement", max_length=20, unique=True, verbose_name='Code unique')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le comptable est actuellement actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.OneToOneField(help_text='Utilisateur Django associé à ce comptable', on_delete=django.db.models.deletion.CASCADE, related_name='comptable', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Comptable',
                'verbose_name_plural': 'Comptables',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='Utilisateur_email_9edad8_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='Utilisateur_role_080ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'is_active_user'], name='Utilisateur_is_acti_38a780_idx'),
        ),
        migrations.AddIndex(
            model_name='professeur',
            index=models.Index(fields=['matricule'], name='Utilisateur_matricu_c8548f_idx'),
        ),
        migrations.AddIndex(
            model_name='professeur',
            index=models.Index(fields=['is_active'], name='Utilisateur_is_acti_f73413_idx'),
        ),
        migrations.AddIndex(
            model_name='comptable',
            index=models.Index(fields=['is_active'], name='Utilisateur_is_acti_c32c73_idx'),
        ),
        migrations.AddIndex(
            model_name='comptable',
            index=models.Index(fields=['created_at'], name='Utilisateur_created_9b743d_idx'),
        ),
        migrations.AddIndex(
            model_name='comptable',
            index=models.Index(fields=['matricule'], name='Utilisateur_matricu_001e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='comptable',
            index=models.Index(fields=['code_unique'], name='Utilisateur_code_un_97490e_idx'),
        ),
    ]
